import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-600 text-slate-200`}
      >
        {/* Desktop Layout - Mevcut tasarımınız */}
        <div className="hidden md:flex flex-1 flex-row h-screen">
          <Navbar/>
          
          <div className="flex-1 overflow-auto">
            {children}
          </div>
        </div>

        {/* Mobile Layout */}
        <div className="md:hidden">
          <Navbar/>
          <div className="pt-16">
            {children}
          </div>
        </div>
        
      </body>
    </html>
  );
}